env:
  node: true
  browser: true
  es2020: true

extends: 
  - 'eslint:recommended'
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
