env:
  browser: true
  es2021: true

extends: 
  - 'eslint:recommended'
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
